/**
 * Generates src/styles/tokens.css from src/styles/tokens.json and records a SHA-256 of the JSON.
 *
 *   pnpm tokens:build         regenerate tokens.css and tokens.sha256
 *   pnpm tokens:check         fail if tokens.css or the checksum is stale
 *
 * tokens.json is the design system (brief, rule 4): measured from the approved prototype until a
 * fuller system is supplied. The dark theme is the default (brief, Design system; Grownz D22);
 * the light theme is the backup, selected with data-theme="light".
 */
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const dir = join(here, '../src/styles');
const srcJson = join(dir, 'tokens.json');
const outCss = join(dir, 'tokens.css');
const outSum = join(dir, 'tokens.sha256');

interface Tokens {
  color: { brand: Record<string, string>; dark: Record<string, string>; light: Record<string, string> };
  font: Record<string, string>;
  fontSize: Record<string, string>;
  fontWeight: Record<string, number>;
  lineHeight: Record<string, number>;
  letterSpacing: Record<string, string>;
  space: Record<string, string>;
  radius: Record<string, string>;
  shadow: Record<string, string>;
  gradient: Record<string, string>;
  motion: Record<string, string>;
}

const kebab = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();

export function toCss(t: Tokens): string {
  const lines: string[] = [];
  const push = (k: string, v: string | number) => lines.push(`  --${k}: ${v};`);
  const theme = (colors: Record<string, string>, shadows: { card: string; float: string }) => {
    for (const [k, v] of Object.entries(colors)) push(`color-${kebab(k)}`, v);
    push('shadow-card', shadows.card);
    push('shadow-float', shadows.float);
  };
  lines.push('/* Generated by scripts/tokens-build.ts from tokens.json. Do not edit by hand. */');
  lines.push(':root {');
  for (const [k, v] of Object.entries(t.color.brand)) push(`brand-${kebab(k)}`, v);
  for (const [k, v] of Object.entries(t.font)) push(`font-${k}`, v);
  for (const [k, v] of Object.entries(t.fontSize)) push(`text-${k}`, v);
  for (const [k, v] of Object.entries(t.fontWeight)) push(`weight-${k}`, v);
  for (const [k, v] of Object.entries(t.lineHeight)) push(`leading-${k}`, v);
  for (const [k, v] of Object.entries(t.letterSpacing)) push(`tracking-${k}`, v);
  for (const [k, v] of Object.entries(t.space)) push(`space-${k}`, v);
  for (const [k, v] of Object.entries(t.radius)) push(`radius-${k}`, v);
  push('shadow-glow', t.shadow['glow'] ?? '');
  for (const [k, v] of Object.entries(t.gradient)) push(`gradient-${kebab(k)}`, v);
  for (const [k, v] of Object.entries(t.motion)) push(`motion-${k}`, v);
  lines.push('}');
  lines.push('/* Dark is the default theme. */');
  lines.push(':root, :root[data-theme="dark"], .theme-dark {');
  theme(t.color.dark, { card: t.shadow['card'] ?? '', float: t.shadow['float'] ?? '' });
  lines.push('}');
  lines.push('/* Light is the backup theme, for print, email captures and a later switch. */');
  lines.push(':root[data-theme="light"], .theme-light {');
  theme(t.color.light, { card: t.shadow['cardLight'] ?? '', float: t.shadow['floatLight'] ?? '' });
  lines.push('}');
  return lines.join('\n') + '\n';
}

const sha = (s: string) => createHash('sha256').update(s).digest('hex');

function main() {
  const raw = readFileSync(srcJson, 'utf8');
  const check = process.argv.includes('--check');
  if (check) {
    const sum = existsSync(outSum) ? readFileSync(outSum, 'utf8').trim() : '';
    const css = existsSync(outCss) ? readFileSync(outCss, 'utf8') : '';
    if (sha(raw) !== sum || css !== toCss(JSON.parse(raw) as Tokens)) {
      console.error('tokens: tokens.css or tokens.sha256 is stale. Run pnpm tokens:build.');
      process.exit(1);
    }
    console.log('tokens: in sync.');
    return;
  }
  writeFileSync(outCss, toCss(JSON.parse(raw) as Tokens), 'utf8');
  writeFileSync(outSum, sha(raw) + '\n', 'utf8');
  console.log(`tokens: wrote ${outCss}`);
}

main();
